-- Phase 2: coaches, teams, pillars, master question bank, team-level questions.

create table public.pillars (
  id text primary key,
  name text not null,
  order_index int not null
);

insert into public.pillars (id, name, order_index) values
  ('technical', 'Technical', 1),
  ('physical', 'Physical', 2),
  ('tactical', 'Tactical', 3),
  ('psychological', 'Psychological', 4),
  ('social', 'Social', 5);

create table public.coaches (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  name text,
  club_name text,
  plan text not null default 'free',
  created_at timestamptz not null default now()
);

-- Backfill any coaches who registered before this table existed.
insert into public.coaches (id, email, name)
select id, email, raw_user_meta_data ->> 'full_name'
from auth.users
on conflict (id) do nothing;

create or replace function public.handle_new_coach()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.coaches (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data ->> 'full_name');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_coach();

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  coach_id uuid not null references public.coaches (id) on delete cascade,
  name text not null,
  age_band text not null check (
    age_band in ('U6-U7', 'U8-U9', 'U10-U11', 'U12-U13', 'U14-U15', 'U16-U17')
  ),
  created_at timestamptz not null default now()
);

-- One team per coach in V1.
create unique index teams_one_per_coach on public.teams (coach_id);

create table public.master_questions (
  id text primary key,
  age_band text not null check (
    age_band in ('U6-U7', 'U8-U9', 'U10-U11', 'U12-U13', 'U14-U15', 'U16-U17')
  ),
  pillar_id text not null references public.pillars (id),
  variant text not null check (
    variant in ('outfield', 'defence', 'midfield', 'attack', 'goalkeeper', 'all')
  ),
  order_index int not null,
  question_text text not null,
  anchor_1 text not null,
  anchor_2 text not null,
  anchor_3 text not null,
  anchor_4 text not null,
  anchor_5 text not null,
  created_at timestamptz not null default now()
);

create table public.team_questions (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams (id) on delete cascade,
  pillar_id text not null references public.pillars (id),
  variant text not null check (
    variant in ('outfield', 'defence', 'midfield', 'attack', 'goalkeeper', 'all')
  ),
  source_master_id text references public.master_questions (id),
  order_index int not null,
  question_text text not null,
  anchor_1 text not null,
  anchor_2 text not null,
  anchor_3 text not null,
  anchor_4 text not null,
  anchor_5 text not null,
  is_custom boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.pillars enable row level security;
alter table public.coaches enable row level security;
alter table public.teams enable row level security;
alter table public.master_questions enable row level security;
alter table public.team_questions enable row level security;

create policy "Authenticated users can read pillars"
  on public.pillars for select to authenticated using (true);

create policy "Authenticated users can read master questions"
  on public.master_questions for select to authenticated using (true);

create policy "Coaches can view their own row"
  on public.coaches for select using (id = auth.uid());

create policy "Coaches can update their own row"
  on public.coaches for update using (id = auth.uid());

create policy "Coaches manage their own teams"
  on public.teams for all
  using (coach_id = auth.uid())
  with check (coach_id = auth.uid());

create policy "Coaches manage their own team questions"
  on public.team_questions for all
  using (team_id in (select id from public.teams where coach_id = auth.uid()))
  with check (team_id in (select id from public.teams where coach_id = auth.uid()));

-- Master question bank seed (216 rows: 4 questions x 6 age bands x 5 pillars,
-- with Technical/Tactical split into 4 position variants from U10-U11 up).
insert into public.master_questions
  (id, age_band, pillar_id, variant, order_index, question_text, anchor_1, anchor_2, anchor_3, anchor_4, anchor_5)
values
('TEC-OUT-U6U7-1', 'U6-U7', 'technical', 'outfield', 1, 'Can the player control (stop) the ball when it comes to them?', 'Ball bounces away; can''t stop it.', 'Traps it occasionally, usually loses control.', 'Stops the ball when it comes slowly.', 'Controls most balls that reach them.', 'Comfortable first touch; controls the ball easily.'),
('TEC-OUT-U6U7-2', 'U6-U7', 'technical', 'outfield', 2, 'Can the player pass the ball to a teammate?', 'Kicks randomly; rarely reaches a teammate.', 'Passes short distances with little accuracy.', 'Reaches a nearby teammate sometimes.', 'Passes accurately to teammates close by.', 'Finds teammates consistently with a clean pass.'),
('TEC-OUT-U6U7-3', 'U6-U7', 'technical', 'outfield', 3, 'Can the player run with the ball under control?', 'Ball runs away as soon as they move.', 'Moves the ball but loses it quickly.', 'Runs with the ball a short way.', 'Keeps the ball close while running.', 'Dribbles with control and changes direction.'),
('TEC-OUT-U6U7-4', 'U6-U7', 'technical', 'outfield', 4, 'Can the player kick the ball with purpose?', 'Miskicks or barely connects with the ball.', 'Kicks it, but with no direction.', 'Kicks toward goal or teammate sometimes.', 'Strikes the ball with reasonable direction.', 'Strikes cleanly and aims where they want.'),
('TEC-OUT-U8U9-1', 'U8-U9', 'technical', 'outfield', 1, 'Does the player have a good first touch under little pressure?', 'Heavy touch; the ball bounces away.', 'Controls only slow, easy balls.', 'Decent first touch when unpressured.', 'Good first touch, sets up the next action.', 'Clean first touch into space every time.'),
('TEC-OUT-U8U9-2', 'U8-U9', 'technical', 'outfield', 2, 'Can the player pass accurately over short distances?', 'Passes are wayward and often overhit.', 'Reaches teammates only occasionally.', 'Accurate over short, simple passes.', 'Passes accurately with good weight nearby.', 'Consistently accurate; weights passes to teammates.'),
('TEC-OUT-U8U9-3', 'U8-U9', 'technical', 'outfield', 3, 'Can the player dribble and beat an opponent?', 'Loses the ball as soon as challenged.', 'Keeps the ball but can''t beat anyone.', 'Beats an opponent occasionally in space.', 'Takes players on and beats them sometimes.', 'Confident dribbler; beats opponents regularly.'),
('TEC-OUT-U8U9-4', 'U8-U9', 'technical', 'outfield', 4, 'Can the player shoot with reasonable technique?', 'Scuffs or miskicks most shots.', 'Shoots, but rarely on target.', 'Hits the target when unpressured.', 'Strikes shots cleanly and on target.', 'Strikes with power and places shots well.'),
('TEC-DEF-U10U11-1', 'U10-U11', 'technical', 'defence', 1, 'Can the defender clear the ball safely under pressure?', 'Miskicks or slices clearances under pressure.', 'Clears sometimes, often straight to opponents.', 'Clears safely when unpressured.', 'Clears the ball safely under pressure.', 'Clears cleanly and finds a teammate when possible.'),
('TEC-DEF-U10U11-2', 'U10-U11', 'technical', 'defence', 2, 'Does the defender time their tackles well?', 'Dives in and mistimes most tackles.', 'Wins tackles only against slower players.', 'Times tackles when the attacker slows.', 'Times tackles well to win the ball.', 'Tackles cleanly; rarely fouls or misses.'),
('TEC-DEF-U10U11-3', 'U10-U11', 'technical', 'defence', 3, 'Can the defender control the ball when it comes to them?', 'Poor touch; loses the ball under pressure.', 'Controls easy balls, panics under pressure.', 'Controls the ball with time.', 'Controls the ball under some pressure.', 'Composed first touch; keeps possession under pressure.'),
('TEC-DEF-U10U11-4', 'U10-U11', 'technical', 'defence', 4, 'Can the defender pass out safely from the back?', 'Hoofs it clear with no target.', 'Passes short but often to opponents.', 'Finds a nearby teammate when unpressured.', 'Passes out to a teammate under pressure.', 'Starts attacks with a calm, accurate pass.'),
('TEC-DEF-U12U13-1', 'U12-U13', 'technical', 'defence', 1, 'Can the defender clear or head the ball away under pressure?', 'Clearances and headers are weak or miscued.', 'Clears low balls, struggles with aerial ones.', 'Clears reliably when unpressured.', 'Clears and heads away well under pressure.', 'Commanding clearances and headers under real pressure.'),
('TEC-DEF-U12U13-2', 'U12-U13', 'technical', 'defence', 2, 'Is the defender''s tackling and interception technique reliable?', 'Mistimes tackles; dives in and fouls.', 'Wins the ball only in easy situations.', 'Reliable tackling, interceptions inconsistent.', 'Tackles and intercepts reliably.', 'Excellent timing; wins the ball cleanly and often.'),
('TEC-DEF-U12U13-3', 'U12-U13', 'technical', 'defence', 3, 'Can the defender control the ball under pressure?', 'First touch fails whenever pressured.', 'Controls with time, panics under pressure.', 'Controls the ball under moderate pressure.', 'Controls cleanly under real pressure.', 'Assured touch; escapes pressure to keep possession.'),
('TEC-DEF-U12U13-4', 'U12-U13', 'technical', 'defence', 4, 'Can the defender play out accurately from the back?', 'Clears aimlessly; gives possession away.', 'Short passes only, often to opponents.', 'Plays out safely when unpressured.', 'Plays out accurately under pressure.', 'Breaks the press with composed, accurate passing.'),
('TEC-DEF-U14U15-1', 'U14-U15', 'technical', 'defence', 1, 'Does the defender defend the ball in the air and on the ground?', 'Beaten in the air and on the ground.', 'Wins ground duels, weak in the air.', 'Competent in both when unpressured.', 'Defends well in the air and on the ground.', 'Dominant in duels; wins the ball decisively.'),
('TEC-DEF-U14U15-2', 'U14-U15', 'technical', 'defence', 2, 'Is the defender''s tackling and interception technique strong?', 'Poor timing; fouls or misses regularly.', 'Wins the ball but often mistimes.', 'Sound technique in straightforward situations.', 'Strong, well-timed tackling and interceptions.', 'Reads and wins the ball cleanly under pressure.'),
('TEC-DEF-U14U15-3', 'U14-U15', 'technical', 'defence', 3, 'Can the defender receive and control under real pressure?', 'Loses the ball under any pressure.', 'Needs space to control safely.', 'Controls under moderate pressure.', 'Receives and controls under real pressure.', 'Composed first touch; comfortable in tight spaces.'),
('TEC-DEF-U14U15-4', 'U14-U15', 'technical', 'defence', 4, 'Can the defender build play accurately from the back?', 'Distribution is rushed and inaccurate.', 'Safe, short passing only.', 'Builds play when given time.', 'Builds play accurately under pressure.', 'Progresses play; passing beats the press.'),
('TEC-DEF-U16U17-1', 'U16-U17', 'technical', 'defence', 1, 'Does the defender win aerial and ground duels convincingly?', 'Loses most duels in the air and ground.', 'Competes but often comes second.', 'Wins routine duels convincingly.', 'Wins aerial and ground duels convincingly.', 'Dominant in every duel; rarely beaten.'),
('TEC-DEF-U16U17-2', 'U16-U17', 'technical', 'defence', 2, 'Is the defender''s defensive technique reliable against quality?', 'Technique breaks down against good attackers.', 'Reliable only against weaker opponents.', 'Sound against most attackers.', 'Reliable technique against quality attackers.', 'Wins the ball cleanly against the best.'),
('TEC-DEF-U16U17-3', 'U16-U17', 'technical', 'defence', 3, 'Can the defender receive, control, and retain under heavy pressure?', 'Panics and loses possession under pressure.', 'Retains possession only with time.', 'Controls under moderate pressure.', 'Controls and retains under heavy pressure.', 'Assured under any pressure; never flustered.'),
('TEC-DEF-U16U17-4', 'U16-U17', 'technical', 'defence', 4, 'Does the defender build and progress play from the back?', 'Cannot be trusted to play out.', 'Only the safe, simple pass.', 'Progresses play in settled moments.', 'Builds and progresses play under pressure.', 'Dictates from the back; passing breaks lines.'),
('TEC-MID-U10U11-1', 'U10-U11', 'technical', 'midfield', 1, 'Can the midfielder control the ball and keep possession?', 'Heavy touch; loses the ball quickly.', 'Controls easy balls, loses it under pressure.', 'Keeps the ball when given time.', 'Controls and keeps the ball under pressure.', 'Rarely loses possession; touch buys time and space.'),
('TEC-MID-U10U11-2', 'U10-U11', 'technical', 'midfield', 2, 'Can the midfielder turn with the ball to play forward?', 'Always plays backwards; never turns.', 'Turns only when there''s lots of space.', 'Turns when unpressured, plays safe otherwise.', 'Turns to play forward when possible.', 'Turns out of pressure to attack quickly.'),
('TEC-MID-U10U11-3', 'U10-U11', 'technical', 'midfield', 3, 'Does the midfielder pass with the right weight and timing?', 'Passes over- or under-hit and poorly timed.', 'Weight and timing right only when unpressured.', 'Reasonable weight, timing sometimes off.', 'Good weight and timing on most passes.', 'Weights passes perfectly into a teammate''s stride.'),
('TEC-MID-U10U11-4', 'U10-U11', 'technical', 'midfield', 4, 'Can the midfielder link play with quick, tidy touches?', 'Slow, heavy touches break up play.', 'Holds the ball too long each time.', 'Links play when there''s little pressure.', 'Links play with quick, tidy touches.', 'One and two-touch play keeps attacks flowing.'),
('TEC-MID-U12U13-1', 'U12-U13', 'technical', 'midfield', 1, 'Can the midfielder control and keep the ball under pressure?', 'Loses the ball under any pressure.', 'Keeps it only with time and space.', 'Retains the ball under moderate pressure.', 'Controls and keeps the ball under pressure.', 'Rarely dispossessed; touch buys time and space.'),
('TEC-MID-U12U13-2', 'U12-U13', 'technical', 'midfield', 2, 'Can the midfielder turn and play forward under pressure?', 'Always plays backwards or sideways.', 'Turns only when given space.', 'Turns forward in settled play.', 'Turns and plays forward under pressure.', 'Turns out of pressure to launch attacks.'),
('TEC-MID-U12U13-3', 'U12-U13', 'technical', 'midfield', 3, 'Does the midfielder pass with the right weight and timing?', 'Passes over- or under-hit and poorly timed.', 'Weight and timing right only when unpressured.', 'Reasonable weight, timing sometimes off.', 'Good weight and timing under pressure.', 'Weights and times passes into a teammate''s stride.'),
('TEC-MID-U12U13-4', 'U12-U13', 'technical', 'midfield', 4, 'Can the midfielder link play with quick, tidy touches?', 'Heavy touches slow the play down.', 'Holds the ball too long each time.', 'Links play in unpressured moments.', 'Links play with quick, tidy touches.', 'Sharp one and two-touch play keeps attacks flowing.'),
('TEC-MID-U14U15-1', 'U14-U15', 'technical', 'midfield', 1, 'Does the midfielder retain the ball under real pressure?', 'Gives the ball away under pressure.', 'Keeps possession only with space.', 'Retains the ball under moderate pressure.', 'Retains the ball under real pressure.', 'Escapes tight pressure and keeps possession consistently.'),
('TEC-MID-U14U15-2', 'U14-U15', 'technical', 'midfield', 2, 'Can the midfielder receive and turn to play forward under pressure?', 'Receives square; always plays backwards.', 'Turns only when unpressured.', 'Turns forward in favourable moments.', 'Receives and turns to play forward under pressure.', 'Consistently turns out of pressure to attack.'),
('TEC-MID-U14U15-3', 'U14-U15', 'technical', 'midfield', 3, 'Is the midfielder''s passing accurate and well-weighted in range?', 'Passing lacks accuracy and weight.', 'Short passing fine, longer passing weak.', 'Accurate short and medium range.', 'Accurate, well-weighted across the range.', 'Dictates play; weighted passes break lines.'),
('TEC-MID-U14U15-4', 'U14-U15', 'technical', 'midfield', 4, 'Does the midfielder combine quickly to keep play flowing?', 'Slow touches break up attacks.', 'Holds the ball rather than combining.', 'Combines when there''s little pressure.', 'Combines quickly to keep play flowing.', 'Slick combinations unlock and speed up attacks.'),
('TEC-MID-U16U17-1', 'U16-U17', 'technical', 'midfield', 1, 'Does the midfielder retain and dictate possession under pressure?', 'Loses possession under real pressure.', 'Keeps the ball only with time.', 'Retains possession under moderate pressure.', 'Retains and dictates possession under pressure.', 'Controls the game; never loses the ball cheaply.'),
('TEC-MID-U16U17-2', 'U16-U17', 'technical', 'midfield', 2, 'Can the midfielder receive, turn, and progress in tight areas?', 'Cannot turn or progress when tight.', 'Progresses only with space.', 'Turns and progresses in moderate pressure.', 'Receives, turns, and progresses in tight areas.', 'Escapes tight areas to drive play forward.'),
('TEC-MID-U16U17-3', 'U16-U17', 'technical', 'midfield', 3, 'Is the midfielder''s passing range accurate and incisive?', 'Limited range; passing lacks accuracy.', 'Reliable short, weak over distance.', 'Accurate across the range in settled play.', 'Accurate, incisive passing across the range.', 'Passing controls and unlocks the game.'),
('TEC-MID-U16U17-4', 'U16-U17', 'technical', 'midfield', 4, 'Does the midfielder combine and control tempo with their touches?', 'Touches are heavy and slow play.', 'Combines only in easy situations.', 'Combines and links in settled spells.', 'Combines and controls tempo with their touches.', 'Dictates tempo; touches set the game''s rhythm.'),
('TEC-ATT-U10U11-1', 'U10-U11', 'technical', 'attack', 1, 'Can the attacker shoot and finish chances?', 'Scuffs or miskicks most shots.', 'Shoots, but rarely on target.', 'Hits the target from good positions.', 'Finishes chances with a clean strike.', 'Composed finisher; takes chances under pressure.'),
('TEC-ATT-U10U11-2', 'U10-U11', 'technical', 'attack', 2, 'Can the attacker beat a defender with the ball?', 'Loses the ball when challenged.', 'Runs into defenders and loses it.', 'Beats a defender in open space.', 'Beats defenders one-v-one fairly often.', 'Skilful dribbler; beats defenders in tight areas.'),
('TEC-ATT-U10U11-3', 'U10-U11', 'technical', 'attack', 3, 'Can the attacker control the ball with a defender close?', 'First touch runs away under pressure.', 'Controls only with space and time.', 'Controls with a defender at distance.', 'Controls the ball with a defender close.', 'Sharp touch; sets up a shot instantly.'),
('TEC-ATT-U10U11-4', 'U10-U11', 'technical', 'attack', 4, 'Can the attacker create a shooting chance quickly?', 'Too slow; the chance is gone.', 'Needs several touches to get a shot.', 'Creates a shot when unpressured.', 'Creates a shooting chance quickly.', 'Turns half-chances into shots in a flash.'),
('TEC-ATT-U12U13-1', 'U12-U13', 'technical', 'attack', 1, 'Can the attacker finish chances with good technique?', 'Poor technique; wastes most chances.', 'Finishes only clear, unpressured chances.', 'Finishes reasonably from good positions.', 'Finishes chances with good technique.', 'Clinical; finishes consistently under pressure.'),
('TEC-ATT-U12U13-2', 'U12-U13', 'technical', 'attack', 2, 'Can the attacker beat defenders with the ball?', 'Loses the ball when challenged.', 'Beats defenders only in space.', 'Beats a defender in favourable situations.', 'Beats defenders one-v-one regularly.', 'Skilful; beats defenders in tight areas.'),
('TEC-ATT-U12U13-3', 'U12-U13', 'technical', 'attack', 3, 'Can the attacker control the ball with defenders close?', 'First touch runs away under pressure.', 'Controls only with time and space.', 'Controls with a defender at distance.', 'Controls with defenders close.', 'Sharp touch; sets up a shot instantly.'),
('TEC-ATT-U12U13-4', 'U12-U13', 'technical', 'attack', 4, 'Can the attacker create a shooting chance quickly?', 'Too slow; the chance disappears.', 'Needs several touches to shoot.', 'Creates a shot when unpressured.', 'Creates a shooting chance quickly.', 'Turns half-chances into shots instantly.'),
('TEC-ATT-U14U15-1', 'U14-U15', 'technical', 'attack', 1, 'Is the attacker''s finishing reliable under pressure?', 'Finishing breaks down under pressure.', 'Finishes only unpressured chances.', 'Reliable when set, inconsistent otherwise.', 'Finishes reliably under pressure.', 'Ruthless; converts difficult chances.'),
('TEC-ATT-U14U15-2', 'U14-U15', 'technical', 'attack', 2, 'Can the attacker beat defenders and create in tight areas?', 'Beaten easily; loses the ball often.', 'Beats defenders only with space.', 'Beats defenders and creates occasionally.', 'Beats defenders and creates in tight areas.', 'Decisive dribbler; unlocks defences one-v-one.'),
('TEC-ATT-U14U15-3', 'U14-U15', 'technical', 'attack', 3, 'Can the attacker control difficult balls with defenders close?', 'Cannot control under close pressure.', 'Controls simple balls only.', 'Controls with a defender nearby.', 'Controls difficult balls with defenders close.', 'First touch beats the defender and creates space.'),
('TEC-ATT-U14U15-4', 'U14-U15', 'technical', 'attack', 4, 'Can the attacker finish quickly with limited time and space?', 'Too slow; chances are lost.', 'Needs time and space to shoot.', 'Finishes quickly in good positions.', 'Finishes quickly with limited time.', 'Lightning release; scores from half-chances.'),
('TEC-ATT-U16U17-1', 'U16-U17', 'technical', 'attack', 1, 'Is the attacker''s finishing of a high standard under pressure?', 'Wasteful; poor technique under pressure.', 'Finishes routine chances only.', 'Sound technique, inconsistent conversion.', 'Finishes to a high standard under pressure.', 'Ruthless finisher; scores the difficult chances.'),
('TEC-ATT-U16U17-2', 'U16-U17', 'technical', 'attack', 2, 'Can the attacker beat defenders and be decisive in the final third?', 'Rarely beats defenders or influences play.', 'Beats defenders but decisions let them down.', 'Beats defenders and contributes at times.', 'Decisive in beating defenders and creating.', 'Wins games with individual quality in tight areas.'),
('TEC-ATT-U16U17-3', 'U16-U17', 'technical', 'attack', 3, 'Can the attacker control and manipulate the ball under pressure?', 'Loses the ball under close pressure.', 'Controls only with time and space.', 'Controls under moderate pressure.', 'Controls and manipulates under pressure.', 'Exceptional touch; creates space instantly.'),
('TEC-ATT-U16U17-4', 'U16-U17', 'technical', 'attack', 4, 'Does the attacker finish quickly and clinically in the box?', 'Slow and wasteful in the box.', 'Needs time to get a shot away.', 'Finishes quickly from clear chances.', 'Finishes quickly and clinically in the box.', 'Deadly in the box; converts the tightest chances.'),
('TEC-GK-U10U11-1', 'U10-U11', 'technical', 'goalkeeper', 1, 'Can the goalkeeper catch or stop shots coming at them?', 'Lets easy shots through; poor handling.', 'Stops some, spills or drops many.', 'Holds shots hit straight at them.', 'Catches or blocks most shots well.', 'Handles shots cleanly and holds firmly.'),
('TEC-GK-U10U11-2', 'U10-U11', 'technical', 'goalkeeper', 2, 'Does the goalkeeper get their body behind the ball?', 'Reaches with hands, body not behind ball.', 'Behind the ball for easy shots only.', 'Gets behind straightforward shots.', 'Usually gets body behind the ball.', 'Always set and behind the ball to save.'),
('TEC-GK-U10U11-3', 'U10-U11', 'technical', 'goalkeeper', 3, 'Can the goalkeeper roll or kick the ball to a teammate?', 'Boots it away with no target.', 'Clears long, rarely to a teammate.', 'Reaches a nearby teammate sometimes.', 'Rolls or passes to teammates accurately.', 'Starts attacks with an accurate throw or pass.'),
('TEC-GK-U10U11-4', 'U10-U11', 'technical', 'goalkeeper', 4, 'Is the goalkeeper comfortable with the ball at their feet?', 'Panics and miskicks with the ball.', 'Uncomfortable; hoofs it clear quickly.', 'Manages simple passes back to them.', 'Controls and passes calmly with feet.', 'Confident in possession; helps build play.'),
('TEC-GK-U12U13-1', 'U12-U13', 'technical', 'goalkeeper', 1, 'Can the goalkeeper catch and hold shots and crosses cleanly?', 'Often spills or drops the ball under pressure.', 'Catches easy balls, parries or fumbles harder ones.', 'Holds routine shots; struggles with crosses and power.', 'Catches most shots and crosses cleanly.', 'Commands the area, catches confidently under pressure.'),
('TEC-GK-U12U13-2', 'U12-U13', 'technical', 'goalkeeper', 2, 'Does the goalkeeper set their feet and body behind the ball?', 'Flat-footed; dives at balls they could save standing.', 'Reacts late, often off-balance when shots come.', 'Sets feet for straight shots, caught out wide.', 'Usually balanced and behind the ball to save.', 'Quick, balanced footwork; gets behind everything reachable.'),
('TEC-GK-U12U13-3', 'U12-U13', 'technical', 'goalkeeper', 3, 'Can the goalkeeper distribute the ball accurately to a teammate?', 'Boots it aimlessly; possession usually lost.', 'Clears long with little accuracy or intention.', 'Finds a teammate when unpressured and simple.', 'Rolls or passes accurately to start attacks.', 'Picks the right pass to beat the first press.'),
('TEC-GK-U12U13-4', 'U12-U13', 'technical', 'goalkeeper', 4, 'Does the goalkeeper handle back-passes and use their feet?', 'Panics with the ball at feet; often miskicks.', 'Only hoofs it clear, uncomfortable in possession.', 'Manages simple back-passes, rushed under pressure.', 'Controls and passes back-passes calmly.', 'Comfortable in possession, acts like an extra defender.'),
('TEC-GK-U14U15-1', 'U14-U15', 'technical', 'goalkeeper', 1, 'Does the goalkeeper handle shots and crosses reliably under pressure?', 'Unreliable handling; spills lead to chances.', 'Holds routine shots, struggles with crosses.', 'Reliable with shots, hesitant on crosses.', 'Handles shots and crosses reliably under pressure.', 'Dominant handler; claims crosses and holds everything.'),
('TEC-GK-U14U15-2', 'U14-U15', 'technical', 'goalkeeper', 2, 'Is the goalkeeper''s footwork and shot-stopping technique sound?', 'Poor footwork; beaten by saveable shots.', 'Set for central shots, weak going wide.', 'Sound technique for straightforward shots.', 'Good footwork; strong shot-stopping across the goal.', 'Excellent technique; makes difficult saves look routine.'),
('TEC-GK-U14U15-3', 'U14-U15', 'technical', 'goalkeeper', 3, 'Can the goalkeeper distribute accurately to start attacks?', 'Distribution is aimless and loses possession.', 'Long clearances only, little accuracy.', 'Accurate over short range, riskier long.', 'Distributes accurately to start attacks.', 'Varied, accurate distribution that beats the press.'),
('TEC-GK-U14U15-4', 'U14-U15', 'technical', 'goalkeeper', 4, 'Does the goalkeeper use their feet to support the defence?', 'A liability with the ball at feet.', 'Only clears; avoids playing out.', 'Plays simple passes under little pressure.', 'Comfortable in possession; supports the defence.', 'Acts as an outfield player when building play.'),
('TEC-GK-U16U17-1', 'U16-U17', 'technical', 'goalkeeper', 1, 'Is the goalkeeper''s handling and command of the area of a high standard?', 'Unconvincing handling; rarely commands the area.', 'Holds shots but stays rooted to the line.', 'Commands the area in straightforward situations.', 'Handles well and commands the area confidently.', 'Dominates the area; claims and holds under pressure.'),
('TEC-GK-U16U17-2', 'U16-U17', 'technical', 'goalkeeper', 2, 'Is the goalkeeper''s shot-stopping technique reliable and strong?', 'Technique breaks down under real pressure.', 'Stops what they should, no more.', 'Reliable on routine shots, beaten by quality.', 'Strong, reliable shot-stopping across the goal.', 'Outstanding shot-stopper; makes match-winning saves.'),
('TEC-GK-U16U17-3', 'U16-U17', 'technical', 'goalkeeper', 3, 'Does the goalkeeper distribute with range, accuracy, and intent?', 'Distribution lacks range and gives possession away.', 'Safe distribution only; little intent.', 'Accurate short, limited long-range threat.', 'Distributes with range, accuracy, and intent.', 'Launches attacks; distribution is a genuine weapon.'),
('TEC-GK-U16U17-4', 'U16-U17', 'technical', 'goalkeeper', 4, 'Is the goalkeeper a reliable extra player in possession?', 'Cannot be trusted with the ball.', 'Plays only the safest, simplest pass.', 'Comfortable under light pressure only.', 'Reliable in possession under real pressure.', 'Composed extra defender; key to building play.'),
('PHY-ALL-U6U7-1', 'U6-U7', 'physical', 'all', 1, 'Can the player run, stop, and change direction with balance?', 'Falls or stumbles often when changing direction.', 'Runs straight but loses balance turning.', 'Turns and stops, sometimes off-balance.', 'Changes direction with control most times.', 'Runs, stops, and turns smoothly and confidently.'),
('PHY-ALL-U6U7-2', 'U6-U7', 'physical', 'all', 2, 'Does the player keep active and try hard all session?', 'Tires quickly; stands still often.', 'Joins in briefly, then drifts off.', 'Active in bursts; needs encouragement.', 'Keeps moving for most of the session.', 'Full of energy throughout; always involved.'),
('PHY-ALL-U6U7-3', 'U6-U7', 'physical', 'all', 3, 'Does the player react quickly to a loose ball?', 'Slow to react; others reach it first.', 'Reacts late; beaten to most balls.', 'Gets to some loose balls nearby.', 'Quick to react and reach loose balls.', 'First to react; wins most loose balls.'),
('PHY-ALL-U6U7-4', 'U6-U7', 'physical', 'all', 4, 'Does the player stay on their feet when bumped?', 'Falls over with any contact at all.', 'Wobbles and often goes to ground.', 'Stays up sometimes, falls under pressure.', 'Keeps balance through light contact.', 'Strong balance; rarely knocked off the ball.'),
('PHY-ALL-U8U9-1', 'U8-U9', 'physical', 'all', 1, 'Can the player change direction quickly without slowing much?', 'Slows right down or stops to turn.', 'Turns awkwardly, losing lots of speed.', 'Changes direction, but loses pace doing it.', 'Turns quickly, keeping most of their speed.', 'Sharp changes of direction at full speed.'),
('PHY-ALL-U8U9-2', 'U8-U9', 'physical', 'all', 2, 'Does the player keep working for the whole session?', 'Stops running after a few minutes.', 'Works hard early, fades quickly.', 'Works in spells, tires in busy periods.', 'Keeps working for most of the session.', 'Same energy at the end as the start.'),
('PHY-ALL-U8U9-3', 'U8-U9', 'physical', 'all', 3, 'Is the player quick over the first few steps?', 'Slow to start; last to react.', 'Gets going late off the mark.', 'Average start; neither quick nor slow.', 'Quick over the first few steps.', 'Explosive first steps; beats others to the ball.'),
('PHY-ALL-U8U9-4', 'U8-U9', 'physical', 'all', 4, 'Does the player stay balanced when challenged for the ball?', 'Easily knocked off the ball by contact.', 'Loses balance when an opponent leans in.', 'Holds up under light contact only.', 'Stays balanced through most challenges.', 'Strong and steady; shrugs off challenges.'),
('PHY-ALL-U10U11-1', 'U10-U11', 'physical', 'all', 1, 'Does the player keep a high work rate across the game?', 'Walks or stands for long spells.', 'Works in short bursts, then rests.', 'Decent effort, but drops off late.', 'Works hard for most of the game.', 'Relentless work rate from start to finish.'),
('PHY-ALL-U10U11-2', 'U10-U11', 'physical', 'all', 2, 'Is the player quick to accelerate into space?', 'Slow to get going; rarely beats others.', 'Reaches top speed too slowly to matter.', 'Accelerates enough in open space.', 'Accelerates quickly into space.', 'Explosive acceleration; regularly beats opponents to it.'),
('PHY-ALL-U10U11-3', 'U10-U11', 'physical', 'all', 3, 'Can the player change direction sharply when running?', 'Slows right down to change direction.', 'Turns sluggishly; loses speed and balance.', 'Changes direction well at moderate speed.', 'Changes direction sharply while running.', 'Explosive, balanced changes of direction at speed.'),
('PHY-ALL-U10U11-4', 'U10-U11', 'physical', 'all', 4, 'Does the player compete physically for the ball?', 'Backs out of physical challenges.', 'Competes only when sure to win.', 'Contests some duels, avoids others.', 'Competes for most physical challenges.', 'Wins physical duels; relishes the contest.'),
('PHY-ALL-U12U13-1', 'U12-U13', 'physical', 'all', 1, 'Does the player maintain effort and running for the full game?', 'Tires early; noticeable drop after minutes.', 'Fades well before the final whistle.', 'Holds up until late, then drops.', 'Keeps running strongly for the full game.', 'Covers ground tirelessly the whole match.'),
('PHY-ALL-U12U13-2', 'U12-U13', 'physical', 'all', 2, 'Is the player strong when shielding or competing for the ball?', 'Easily shrugged off the ball.', 'Holds the ball only against weaker opponents.', 'Shields the ball in some situations.', 'Holds off opponents to protect the ball.', 'Strong in duels; wins the ball consistently.'),
('PHY-ALL-U12U13-3', 'U12-U13', 'physical', 'all', 3, 'Does the player show speed to beat opponents to the ball?', 'Beaten to most balls in a race.', 'Loses most sprints for the ball.', 'Wins races when starting level.', 'Regularly beats opponents to the ball.', 'Rapid; wins races even starting behind.'),
('PHY-ALL-U12U13-4', 'U12-U13', 'physical', 'all', 4, 'Can the player make repeated recovery runs?', 'One effort, then jogs or stops.', 'Recovers slowly; often too late.', 'Recovers when the danger is obvious.', 'Makes repeated recovery runs when needed.', 'Sprints back repeatedly without dropping off.'),
('PHY-ALL-U14U15-1', 'U14-U15', 'physical', 'all', 1, 'Does the player sustain a high intensity across the whole match?', 'Intensity drops sharply after early effort.', 'Struggles to maintain tempo past halfway.', 'Holds intensity until the closing stages.', 'Sustains high intensity for the full match.', 'Same high tempo in the last minute.'),
('PHY-ALL-U14U15-2', 'U14-U15', 'physical', 'all', 2, 'Is the player strong in physical duels?', 'Loses most physical battles for the ball.', 'Competes but comes off second best.', 'Wins duels against similar opponents.', 'Wins most physical duels comfortably.', 'Dominant physically; rarely loses a duel.'),
('PHY-ALL-U14U15-3', 'U14-U15', 'physical', 'all', 3, 'Does the player have the pace to affect the game?', 'Lacks the speed to influence play.', 'Rarely uses pace to gain advantage.', 'Pace helps in some situations.', 'Uses pace to beat opponents regularly.', 'Game-changing pace; stretches defences repeatedly.'),
('PHY-ALL-U14U15-4', 'U14-U15', 'physical', 'all', 4, 'Can the player produce repeated sprints without fading?', 'One sprint, then noticeably slower.', 'Second and third sprints drop off fast.', 'Repeats efforts, but tires by late game.', 'Repeats sprints with little drop-off.', 'Repeats maximal sprints throughout the game.'),
('PHY-ALL-U16U17-1', 'U16-U17', 'physical', 'all', 1, 'Does the player maintain athletic output for the whole game?', 'Output falls away well before full time.', 'Noticeable decline in the second half.', 'Holds up until the final ten minutes.', 'Maintains output across the whole game.', 'As athletic at the end as the start.'),
('PHY-ALL-U16U17-2', 'U16-U17', 'physical', 'all', 2, 'Is the player strong and robust in physical situations?', 'Weak in contact; easily knocked off balance.', 'Competes physically only against weaker opponents.', 'Holds their own in most physical situations.', 'Strong and robust in physical situations.', 'Physically imposing; wins contact and holds firm.'),
('PHY-ALL-U16U17-3', 'U16-U17', 'physical', 'all', 3, 'Does the player show explosive power when it matters?', 'Lacks explosive power in key moments.', 'Rarely produces a decisive burst of power.', 'Shows explosive power in some situations.', 'Produces explosive power in key moments.', 'Explosively powerful; decisive in the biggest moments.'),
('PHY-ALL-U16U17-4', 'U16-U17', 'physical', 'all', 4, 'Can the player recover quickly between high-intensity efforts?', 'Needs long rest after each effort.', 'Slow to recover; efforts drop off.', 'Recovers adequately in normal passages.', 'Recovers quickly between intense efforts.', 'Near-instant recovery; ready for the next sprint.'),
('TAC-OUT-U6U7-1', 'U6-U7', 'tactical', 'outfield', 1, 'Does the player move into space away from the crowd?', 'Follows the ball in a crowd constantly.', 'Stays in the pack, rarely finds space.', 'Sometimes moves out to find space.', 'Often moves into space away from others.', 'Always finds space; avoids the crowd well.'),
('TAC-OUT-U6U7-2', 'U6-U7', 'tactical', 'outfield', 2, 'Does the player look for a teammate to pass to?', 'Only looks at the ball, never teammates.', 'Kicks it away without looking up.', 'Sometimes spots a teammate before passing.', 'Usually looks for a teammate to pass to.', 'Regularly finds teammates with a good pass.'),
('TAC-OUT-U6U7-3', 'U6-U7', 'tactical', 'outfield', 3, 'Does the player try to win the ball back?', 'Stops or stands when the ball is lost.', 'Watches others try to win it.', 'Chases the ball sometimes.', 'Tries to win the ball back most times.', 'First to chase; keen to win it back.'),
('TAC-OUT-U6U7-4', 'U6-U7', 'tactical', 'outfield', 4, 'Does the player know which way to attack and defend?', 'Often runs toward the wrong goal.', 'Unsure which way to go without help.', 'Knows the direction most of the time.', 'Attacks and defends the right way.', 'Always clear on which way to play.'),
('TAC-OUT-U8U9-1', 'U8-U9', 'tactical', 'outfield', 1, 'Does the player find space to receive the ball?', 'Stands still or hides behind opponents.', 'Moves only toward the ball.', 'Finds space when it''s obvious.', 'Regularly finds space to receive.', 'Constantly finds good space to receive.'),
('TAC-OUT-U8U9-2', 'U8-U9', 'tactical', 'outfield', 2, 'Does the player look around before getting the ball?', 'Never looks up; surprised by opponents.', 'Glances rarely, mostly head down.', 'Looks up when reminded.', 'Usually checks around before receiving.', 'Scans early; knows what''s around them.'),
('TAC-OUT-U8U9-3', 'U8-U9', 'tactical', 'outfield', 3, 'Does the player support the teammate on the ball?', 'Stands and watches the ball-carrier.', 'Too far away to offer help.', 'Supports when the ball is close.', 'Moves to support the ball-carrier.', 'Always offers a useful passing option.'),
('TAC-OUT-U8U9-4', 'U8-U9', 'tactical', 'outfield', 4, 'Does the player react and recover when the ball is lost?', 'Switches off after losing the ball.', 'Reacts slowly; jogs back late.', 'Recovers when the danger is clear.', 'Reacts quickly to recover position.', 'First to react; presses or recovers immediately.'),
('TAC-DEF-U10U11-1', 'U10-U11', 'tactical', 'defence', 1, 'Does the defender get goalside of their opponent (between them and goal)?', 'Ball-watches; often caught the wrong side of their opponent.', 'Sometimes goalside, but loses position when the ball moves.', 'Usually goalside when the ball is near them.', 'Stays goalside and adjusts as the play shifts.', 'Always goalside; positions early to block the danger.'),
('TAC-DEF-U10U11-2', 'U10-U11', 'tactical', 'defence', 2, 'Does the defender stay on their feet and delay rather than diving in?', 'Dives in early; easily beaten by a dribble.', 'Rushes out to tackle, mistimes it often.', 'Sometimes jockeys, sometimes lunges in too soon.', 'Usually stays on feet and delays the attacker.', 'Patiently jockeys, forces mistakes, tackles at the right moment.'),
('TAC-DEF-U10U11-3', 'U10-U11', 'tactical', 'defence', 3, 'Does the defender track their runner instead of ball-watching?', 'Watches the ball; lets runners go past unmarked.', 'Notices runners late, often after they''ve received.', 'Tracks the obvious runner but misses others.', 'Tracks their runner and stays close to them.', 'Tracks runners early and reads the next pass.'),
('TAC-DEF-U10U11-4', 'U10-U11', 'tactical', 'defence', 4, 'When the team loses the ball, does the defender recover toward goal?', 'Stops or stands still after losing possession.', 'Reacts slowly; jogs back without urgency.', 'Recovers, but only when the danger is obvious.', 'Recovers quickly toward their own goal.', 'Sprints back first, organises others as they recover.'),
('TAC-DEF-U12U13-1', 'U12-U13', 'tactical', 'defence', 1, 'Does the defender position themselves to protect the goal and cover space?', 'Out of position; leaves dangerous space open.', 'Marks the ball, forgets the space behind.', 'Covers space when the danger is obvious.', 'Positions well to protect goal and space.', 'Reads danger early; covers space before it''s needed.'),
('TAC-DEF-U12U13-2', 'U12-U13', 'tactical', 'defence', 2, 'Does the defender defend one-v-one effectively?', 'Beaten easily; dives in or backs off.', 'Wins the ball only against weak attackers.', 'Delays well but mistimes the tackle.', 'Jockeys and tackles one-v-one effectively.', 'Rarely beaten; times tackles and interceptions superbly.'),
('TAC-DEF-U12U13-3', 'U12-U13', 'tactical', 'defence', 3, 'Does the defender mark and track runners in behind?', 'Loses runners; caught watching the ball.', 'Tracks the first runner, loses secondary ones.', 'Tracks runners when they''re obvious.', 'Marks and tracks runners in behind well.', 'Anticipates runs; steps out or tracks decisively.'),
('TAC-DEF-U12U13-4', 'U12-U13', 'tactical', 'defence', 4, 'Does the defender recover and cover teammates?', 'No recovery; leaves teammates exposed.', 'Recovers late, rarely covers others.', 'Recovers for themselves, not for teammates.', 'Recovers quickly and covers teammates.', 'Organises cover; first to protect the danger.'),
('TAC-DEF-U14U15-1', 'U14-U15', 'tactical', 'defence', 1, 'Does the defender read the game and anticipate danger?', 'Reacts late; always a step behind play.', 'Anticipates only the most obvious threats.', 'Reads straightforward situations well.', 'Anticipates danger and acts early.', 'Reads the game superbly; snuffs out attacks early.'),
('TAC-DEF-U14U15-2', 'U14-U15', 'tactical', 'defence', 2, 'Does the defender make good decisions when to engage or hold?', 'Dives in or backs off at wrong moments.', 'Engages or holds without clear reason.', 'Decisions are sound in simple situations.', 'Chooses well when to engage or hold.', 'Masterful judgement; forces attackers into mistakes.'),
('TAC-DEF-U14U15-3', 'U14-U15', 'tactical', 'defence', 3, 'Does the defender defend as part of a unit?', 'Defends alone; ignores the defensive line.', 'Holds a line only when reminded.', 'Works with the unit in settled play.', 'Defends well as part of the unit.', 'Marshals the line; keeps the unit compact.'),
('TAC-DEF-U14U15-4', 'U14-U15', 'tactical', 'defence', 4, 'Does the defender deal with crosses and defend the box?', 'Loses markers and attackers in the box.', 'Struggles to clear or head under pressure.', 'Deals with straightforward crosses only.', 'Defends crosses and the box reliably.', 'Dominant in the box; heads and clears authoritatively.'),
('TAC-DEF-U16U17-1', 'U16-U17', 'tactical', 'defence', 1, 'Does the defender consistently read and control defensive situations?', 'Repeatedly caught out; poor game reading.', 'Reads the game only in easy phases.', 'Controls most straightforward defensive situations.', 'Reads and controls defensive situations consistently.', 'Reads at a high level; neutralises danger early.'),
('TAC-DEF-U16U17-2', 'U16-U17', 'tactical', 'defence', 2, 'Does the defender defend one-v-one against quality attackers?', 'Beaten regularly by good attackers.', 'Competes but loses key one-v-one battles.', 'Holds his own against most attackers.', 'Wins one-v-one battles against quality attackers.', 'Rarely beaten; dominates even top attackers.'),
('TAC-DEF-U16U17-3', 'U16-U17', 'tactical', 'defence', 3, 'Does the defender organise and lead the defensive unit?', 'Offers no organisation; unit lacks shape.', 'Organises only when prompted by others.', 'Organises the unit in settled moments.', 'Organises and leads the defensive unit.', 'Commands the defence; dictates line and shape.'),
('TAC-DEF-U16U17-4', 'U16-U17', 'tactical', 'defence', 4, 'Does the defender defend the box and win aerial duels?', 'Loses aerial duels and box battles.', 'Competes in the air inconsistently.', 'Wins routine aerial and box duels.', 'Wins aerial duels and defends the box well.', 'Dominant aerially; commands the entire box.'),
('TAC-MID-U10U11-1', 'U10-U11', 'tactical', 'midfield', 1, 'Does the midfielder move into space to offer a passing option?', 'Stands still; rarely available for a pass.', 'Moves toward the ball, crowding the passer.', 'Finds space sometimes, but drifts out of play.', 'Regularly moves into space to offer an angle.', 'Constantly repositions to stay available across the pitch.'),
('TAC-MID-U10U11-2', 'U10-U11', 'tactical', 'midfield', 2, 'Does the midfielder check their shoulders before receiving?', 'Never looks; surprised by pressure when the ball arrives.', 'Glances only when reminded, rarely before receiving.', 'Checks once, but misses pressure from behind.', 'Scans before receiving and turns away from pressure.', 'Scans early and often; always knows their options.'),
('TAC-MID-U10U11-3', 'U10-U11', 'tactical', 'midfield', 3, 'Does the midfielder link play rather than always dribbling?', 'Always dribbles; rarely passes to teammates.', 'Holds the ball too long before losing it.', 'Passes when easy, dribbles into trouble otherwise.', 'Usually passes and moves to keep play flowing.', 'Links play quickly, choosing pass or dribble well.'),
('TAC-MID-U10U11-4', 'U10-U11', 'tactical', 'midfield', 4, 'Does the midfielder work both ways to support attack and defence?', 'Stays in one area; watches play go by.', 'Involved in spells, but often caught out of position.', 'Supports the attack but is slow to recover defensively.', 'Supports attack and recovers to help defend.', 'Tirelessly links both ends, always in the game.'),
('TAC-MID-U12U13-1', 'U12-U13', 'tactical', 'midfield', 1, 'Does the midfielder position to receive and progress the ball?', 'Hides or gets caught in traffic.', 'Available only for a simple sideways pass.', 'Receives well, but rarely progresses play.', 'Positions to receive and move play forward.', 'Always finds pockets to receive and progress.'),
('TAC-MID-U12U13-2', 'U12-U13', 'tactical', 'midfield', 2, 'Does the midfielder scan and play with awareness of pressure?', 'Head down; caught in possession repeatedly.', 'Aware only when unpressured.', 'Scans in settled play, caught under pressure.', 'Scans and plays aware of pressure.', 'Constant awareness; escapes pressure with first touch.'),
('TAC-MID-U12U13-3', 'U12-U13', 'tactical', 'midfield', 3, 'Does the midfielder pick the right pass to keep or progress?', 'Forces passes; frequently gives possession away.', 'Safe passes only; rarely progresses play.', 'Mixes safe and progressive inconsistently.', 'Picks the right pass to keep or progress.', 'Dictates tempo; consistently finds progressive passes.'),
('TAC-MID-U12U13-4', 'U12-U13', 'tactical', 'midfield', 4, 'Does the midfielder contribute in both boxes?', 'Contributes in neither box.', 'Joins attacks but neglects defensive duties.', 'Covers defensively but rarely joins attacks.', 'Contributes in both boxes when needed.', 'Influences both boxes; a genuine all-round threat.'),
('TAC-MID-U14U15-1', 'U14-U15', 'tactical', 'midfield', 1, 'Does the midfielder control the tempo of the game?', 'No influence on tempo; plays at one speed.', 'Follows the game''s tempo, rarely sets it.', 'Controls tempo in settled periods.', 'Controls and varies the tempo well.', 'Dictates tempo; speeds up or slows the game.'),
('TAC-MID-U14U15-2', 'U14-U15', 'tactical', 'midfield', 2, 'Does the midfielder receive under pressure and keep possession?', 'Loses the ball under any real pressure.', 'Keeps it only with time and space.', 'Retains possession in moderate pressure.', 'Receives under pressure and keeps possession.', 'Escapes tight pressure and retains possession consistently.'),
('TAC-MID-U14U15-3', 'U14-U15', 'tactical', 'midfield', 3, 'Does the midfielder create and break lines with passing?', 'Passing is safe and rarely threatens.', 'Breaks lines only when it''s obvious.', 'Progresses play, creates occasionally.', 'Breaks lines and creates chances regularly.', 'Unlocks defences; passing is a real weapon.'),
('TAC-MID-U14U15-4', 'U14-U15', 'tactical', 'midfield', 4, 'Does the midfielder cover ground and impact attack and defence?', 'Limited running; affects neither attack nor defence.', 'Works hard but affects only one end.', 'Contributes to both attack and defence in spells.', 'Covers ground and impacts attack and defence.', 'Dominates box to box; drives attack and defence.'),
('TAC-MID-U16U17-1', 'U16-U17', 'tactical', 'midfield', 1, 'Does the midfielder control games with and without the ball?', 'Passenger; little control over the game.', 'Influences only when the game is comfortable.', 'Controls games in favourable moments.', 'Controls games with and without the ball.', 'Dominates games; dictates play in every phase.'),
('TAC-MID-U16U17-2', 'U16-U17', 'tactical', 'midfield', 2, 'Does the midfielder receive on the half-turn to progress play?', 'Receives square; forced backwards under pressure.', 'Half-turns only when unpressured.', 'Half-turns in favourable moments.', 'Receives on the half-turn to progress under pressure.', 'Always opens out on the half-turn to attack.'),
('TAC-MID-U16U17-3', 'U16-U17', 'tactical', 'midfield', 3, 'Does the midfielder combine creativity with control in passing?', 'Either safe or careless; no balance.', 'Creative but loses possession too often.', 'Balances creativity and control inconsistently.', 'Combines creativity and control in passing.', 'Controls and unlocks games; exceptional passing range.'),
('TAC-MID-U16U17-4', 'U16-U17', 'tactical', 'midfield', 4, 'Does the midfielder dominate the physical and territorial battle?', 'Overrun; loses the midfield battle.', 'Competes but is often second best.', 'Holds his own in the midfield battle.', 'Wins the physical and territorial battle.', 'Dominates midfield; imposes control territorially.'),
('TAC-ATT-U10U11-1', 'U10-U11', 'tactical', 'attack', 1, 'Does the attacker make runs to get in behind defenders?', 'Stays still; waits for the ball to feet.', 'Runs only after the ball is played.', 'Makes obvious runs, but times them poorly.', 'Regularly runs in behind at the right time.', 'Times runs to beat the defence and stay onside.'),
('TAC-ATT-U10U11-2', 'U10-U11', 'tactical', 'attack', 2, 'Does the attacker find space to receive facing the goal?', 'Receives with back to goal, gets crowded out.', 'Drifts into space occasionally, mostly marked.', 'Finds space when the ball is close.', 'Gets free to receive facing forward.', 'Constantly finds pockets to turn and attack.'),
('TAC-ATT-U10U11-3', 'U10-U11', 'tactical', 'attack', 3, 'When the team loses the ball, does the attacker press?', 'Stops working; waits up the pitch.', 'Presses half-heartedly, easily played around.', 'Presses when the ball is near them.', 'Presses the defenders quickly after losing it.', 'Leads the press, triggering teammates to follow.'),
('TAC-ATT-U10U11-4', 'U10-U11', 'tactical', 'attack', 4, 'Does the attacker try to take defenders on near goal?', 'Avoids one-v-ones; passes backwards instead.', 'Tries only when there''s no pressure.', 'Takes players on sometimes, often loses it.', 'Regularly takes defenders on in the final third.', 'Beats defenders confidently and creates chances.'),
('TAC-ATT-U12U13-1', 'U12-U13', 'tactical', 'attack', 1, 'Does the attacker time runs in behind the defence?', 'Static; offers no threat in behind.', 'Runs too early or too late repeatedly.', 'Times runs when the pass is obvious.', 'Times runs in behind the defence well.', 'Expertly times runs; stretches and beats defences.'),
('TAC-ATT-U12U13-2', 'U12-U13', 'tactical', 'attack', 2, 'Does the attacker create space to receive and turn?', 'Easily marked; can''t get free.', 'Receives facing own goal, gets crowded.', 'Finds space in favourable moments.', 'Creates space to receive and turn.', 'Loses markers constantly; always available to attack.'),
('TAC-ATT-U12U13-3', 'U12-U13', 'tactical', 'attack', 3, 'Does the attacker lead the press from the front?', 'Doesn''t press; leaves teammates exposed.', 'Presses without a trigger, easily bypassed.', 'Presses when the ball is near.', 'Presses well and cuts off options.', 'Leads and directs the press intelligently.'),
('TAC-ATT-U12U13-4', 'U12-U13', 'tactical', 'attack', 4, 'Does the attacker beat defenders and threaten goal?', 'Rarely beats defenders or threatens goal.', 'Beats defenders but wastes the chance.', 'Beats defenders in favourable situations.', 'Regularly beats defenders and threatens goal.', 'Decisive; beats defenders and creates or scores.'),
('TAC-ATT-U14U15-1', 'U14-U15', 'tactical', 'attack', 1, 'Does the attacker''s movement create and exploit space?', 'Static movement; creates nothing.', 'Moves, but into predictable areas.', 'Creates space in favourable situations.', 'Movement creates and exploits space.', 'Clever movement constantly unbalances defences.'),
('TAC-ATT-U14U15-2', 'U14-U15', 'tactical', 'attack', 2, 'Does the attacker combine and link with teammates?', 'Isolated; rarely links with teammates.', 'Holds the ball rather than combining.', 'Links in simple situations only.', 'Combines and links play with teammates.', 'Orchestrates attacks; combinations unlock defences.'),
('TAC-ATT-U14U15-3', 'U14-U15', 'tactical', 'attack', 3, 'Does the attacker press and defend from the front effectively?', 'Offers no defensive work from the front.', 'Presses without purpose or timing.', 'Presses effectively when reminded.', 'Presses and defends from the front well.', 'Sets the defensive tone from the front.'),
('TAC-ATT-U14U15-4', 'U14-U15', 'tactical', 'attack', 4, 'Is the attacker a consistent goal threat?', 'Rarely a threat on goal.', 'Threatens only from clear chances.', 'Threatens goal in good situations.', 'A consistent threat on goal.', 'Ruthless; converts and creates threats repeatedly.'),
('TAC-ATT-U16U17-1', 'U16-U17', 'tactical', 'attack', 1, 'Does the attacker''s movement consistently beat and unbalance defences?', 'Predictable; defences handle them easily.', 'Occasional threat, mostly well-marshalled.', 'Unbalances defences in favourable moments.', 'Movement consistently beats and unbalances defences.', 'Relentless movement; defences cannot contain them.'),
('TAC-ATT-U16U17-2', 'U16-U17', 'tactical', 'attack', 2, 'Does the attacker link, create, and finish at a high level?', 'Contributes little to creating or finishing.', 'Does one of link, create, finish.', 'Contributes across phases inconsistently.', 'Links, creates, and finishes at a high level.', 'Decisive in all three; wins games alone.'),
('TAC-ATT-U16U17-3', 'U16-U17', 'tactical', 'attack', 3, 'Does the attacker lead pressing and structure from the front?', 'No pressing; undermines the team''s structure.', 'Presses individually, ignores the structure.', 'Presses within structure in spells.', 'Leads pressing and defensive structure from the front.', 'Orchestrates the press; sets the team''s defensive tone.'),
('TAC-ATT-U16U17-4', 'U16-U17', 'tactical', 'attack', 4, 'Is the attacker a decisive, reliable goal threat?', 'Unreliable; rarely decisive in front of goal.', 'Takes only the simplest chances.', 'Decisive in good chances, inconsistent otherwise.', 'A decisive, reliable goal threat.', 'Prolific finisher; scores in most games.'),
('TAC-GK-U10U11-1', 'U10-U11', 'tactical', 'goalkeeper', 1, 'Does the goalkeeper stand in a good position for their goal?', 'Off their line or badly positioned often.', 'Positioned reasonably only for central shots.', 'Fair position when the ball is central.', 'Positions well for most shots.', 'Reads angles; positions early to narrow shots.'),
('TAC-GK-U10U11-2', 'U10-U11', 'tactical', 'goalkeeper', 2, 'Does the goalkeeper decide well whether to come or stay?', 'Rushes out or stays when wrong.', 'Hesitates; often caught in between.', 'Right decision in simple situations.', 'Usually decides well to come or stay.', 'Reads the situation; comes or stays decisively.'),
('TAC-GK-U10U11-3', 'U10-U11', 'tactical', 'goalkeeper', 3, 'Does the goalkeeper talk to and organise the defenders?', 'Silent; gives defenders no help.', 'Speaks only when the ball is close.', 'Gives simple instructions sometimes.', 'Talks to and organises the defenders.', 'Commands the area; constantly organises the defence.'),
('TAC-GK-U10U11-4', 'U10-U11', 'tactical', 'goalkeeper', 4, 'Does the goalkeeper deal with balls played behind the defence?', 'Stays on the line; leaves through-balls.', 'Reacts late to balls in behind.', 'Deals with obvious through-balls only.', 'Comes out to deal with balls in behind.', 'Sweeps behind the defence; reads danger early.'),
('TAC-GK-U12U13-1', 'U12-U13', 'tactical', 'goalkeeper', 1, 'Does the goalkeeper position and angle correctly for shots?', 'Poor angles; leaves gaps to shoot at.', 'Sets central angles, exposed out wide.', 'Positions well for straightforward shots.', 'Angles and positions correctly for shots.', 'Narrows angles superbly; makes goal look small.'),
('TAC-GK-U12U13-2', 'U12-U13', 'tactical', 'goalkeeper', 2, 'Does the goalkeeper judge crosses and when to claim?', 'Misjudges crosses; stuck on the line.', 'Comes for easy crosses only.', 'Judges central crosses reasonably.', 'Judges crosses and claims when right.', 'Dominates crosses; claims decisively under pressure.'),
('TAC-GK-U12U13-3', 'U12-U13', 'tactical', 'goalkeeper', 3, 'Does the goalkeeper organise and command the defence?', 'Offers no organisation to the defence.', 'Organises only in obvious situations.', 'Gives instructions in settled play.', 'Organises and commands the defence well.', 'Marshals the defence; sets the line and shape.'),
('TAC-GK-U12U13-4', 'U12-U13', 'tactical', 'goalkeeper', 4, 'Does the goalkeeper sweep behind the defensive line?', 'Rooted to the goal; leaves space behind.', 'Slow to react to balls in behind.', 'Sweeps obvious through-balls only.', 'Sweeps behind the defensive line well.', 'Aggressive sweeper; kills danger before it develops.'),
('TAC-GK-U14U15-1', 'U14-U15', 'tactical', 'goalkeeper', 1, 'Does the goalkeeper''s positioning consistently narrow the shooter''s options?', 'Poor positioning gifts scoring chances.', 'Positions well for central efforts only.', 'Sound positioning in routine situations.', 'Positioning consistently narrows options.', 'Reads shooters; positioning makes scoring very hard.'),
('TAC-GK-U14U15-2', 'U14-U15', 'tactical', 'goalkeeper', 2, 'Does the goalkeeper command the box on crosses and set-pieces?', 'Passive; never leaves the line.', 'Claims only the simplest crosses.', 'Commands the box in easy situations.', 'Commands the box on crosses and set-pieces.', 'Dominant; owns the box under heavy pressure.'),
('TAC-GK-U14U15-3', 'U14-U15', 'tactical', 'goalkeeper', 3, 'Does the goalkeeper organise the defensive line and set-pieces?', 'No organisation; defence lacks shape.', 'Organises only when prompted.', 'Organises in settled defensive moments.', 'Organises the line and set-pieces well.', 'Directs the defence; marshals every set-piece.'),
('TAC-GK-U14U15-4', 'U14-U15', 'tactical', 'goalkeeper', 4, 'Does the goalkeeper act as a sweeper behind the line?', 'Never sweeps; caught on the line.', 'Reacts too slowly to sweep effectively.', 'Sweeps when the danger is clear.', 'Sweeps effectively behind the line.', 'Proactive sweeper; defends a high line confidently.'),
('TAC-GK-U16U17-1', 'U16-U17', 'tactical', 'goalkeeper', 1, 'Is the goalkeeper''s positioning and game reading of a high level?', 'Repeatedly caught out by poor positioning.', 'Reads only straightforward shooting situations.', 'Positioning sound in most situations.', 'Positioning and reading at a high level.', 'Reads superbly; positioning neutralises chances before shots.'),
('TAC-GK-U16U17-2', 'U16-U17', 'tactical', 'goalkeeper', 2, 'Does the goalkeeper dominate the box against crosses and pressure?', 'Dominated in the box; stays rooted.', 'Claims only uncontested crosses.', 'Commands the box in routine situations.', 'Dominates the box against crosses and pressure.', 'Owns the box entirely; commands under any pressure.'),
('TAC-GK-U16U17-3', 'U16-U17', 'tactical', 'goalkeeper', 3, 'Does the goalkeeper lead and organise the whole defence?', 'Provides no leadership to the defence.', 'Organises only in simple phases.', 'Leads the defence in settled play.', 'Leads and organises the whole defence.', 'Commands the defence; dictates line, shape, and set-pieces.'),
('TAC-GK-U16U17-4', 'U16-U17', 'tactical', 'goalkeeper', 4, 'Does the goalkeeper sweep and support a high defensive line?', 'Cannot support a high line at all.', 'Hesitant; sweeps too late to help.', 'Sweeps when danger is obvious.', 'Sweeps and supports a high line well.', 'Sweeps proactively; lets the defence push high.'),
('PSY-ALL-U6U7-1', 'U6-U7', 'psychological', 'all', 1, 'How does the player respond after making a mistake?', 'Cries or stops playing when it goes wrong.', 'Gets upset and needs comforting before continuing.', 'Looks deflated, but carries on after a moment.', 'Shrugs it off and keeps playing happily.', 'Not bothered at all; tries again straight away.'),
('PSY-ALL-U6U7-2', 'U6-U7', 'psychological', 'all', 2, 'Does the player pay attention during the session?', 'Wanders off or gets distracted almost immediately.', 'Watches other things unless spoken to directly.', 'Listens in short bursts, then drifts away.', 'Pays attention for most of the session.', 'Focused and listening throughout for their age.'),
('PSY-ALL-U6U7-3', 'U6-U7', 'psychological', 'all', 3, 'Is the player happy to join in and try things?', 'Hangs back; reluctant to get involved at all.', 'Joins in only with lots of encouragement.', 'Takes part, but sticks to what feels safe.', 'Happily joins in and tries new things.', 'Can''t wait to get involved and try everything.'),
('PSY-ALL-U6U7-4', 'U6-U7', 'psychological', 'all', 4, 'Does the player keep going without being told to?', 'Stops as soon as the coach looks away.', 'Only tries when directly encouraged.', 'Has a go, but gives up quickly.', 'Keeps trying for most of the session.', 'Full effort throughout without any prompting.'),
('PSY-ALL-U8U9-1', 'U8-U9', 'psychological', 'all', 1, 'How does the player respond after making a mistake?', 'Very upset or angry; it ruins the rest of their session.', 'Sulks and hides from the ball for a while.', 'Recovers with a bit of encouragement from others.', 'Gets over it quickly and stays involved.', 'Bounces back instantly and tries the same thing again.'),
('PSY-ALL-U8U9-2', 'U8-U9', 'psychological', 'all', 2, 'Does the player stay focused during the session?', 'Constantly distracted; rarely listens or watches play.', 'Focuses only when the ball is near them.', 'Concentrates in busy moments, drifts when waiting.', 'Stays focused for most of the session.', 'Consistently switched on, even when not involved.'),
('PSY-ALL-U8U9-3', 'U8-U9', 'psychological', 'all', 3, 'Is the player confident to try things with the ball?', 'Avoids the ball; scared to make a mistake.', 'Only tries the safe, simple option.', 'Tries things when there''s little pressure.', 'Confidently tries skills, even when it''s tricky.', 'Always wants the ball and takes on challenges.'),
('PSY-ALL-U8U9-4', 'U8-U9', 'psychological', 'all', 4, 'Does the player show effort without being told?', 'Stops or coasts unless the coach prompts them.', 'Works hard only in the fun bits.', 'Tries steadily, but fades when tired.', 'Works hard for most of the session alone.', 'Gives full effort throughout and encourages others.'),
('PSY-ALL-U10U11-1', 'U10-U11', 'psychological', 'all', 1, 'How does the player respond after making a mistake?', 'Visibly upset or angry; the mistake affects them for minutes.', 'Sulks or goes quiet briefly, hiding from the ball afterwards.', 'Recovers, but only with encouragement from a coach or teammate.', 'Shakes it off quickly on their own and stays involved.', 'Recovers instantly, stays positive, and tries the same thing again.'),
('PSY-ALL-U10U11-2', 'U10-U11', 'psychological', 'all', 2, 'Does the player stay focused throughout the session?', 'Easily distracted; loses attention within seconds of not being involved.', 'Focuses only when directly on the ball; drifts off otherwise.', 'Stays engaged in busy moments but switches off during waits.', 'Mostly attentive throughout, needing only occasional reminders.', 'Consistently switched on, tracking play even when not involved.'),
('PSY-ALL-U10U11-3', 'U10-U11', 'psychological', 'all', 3, 'Is the player willing to get on the ball and try things?', 'Hides from the ball; avoids involvement, especially when losing.', 'Takes the ball only in safe, pressure-free situations.', 'Gets involved willingly, but avoids risk after a mistake.', 'Regularly wants the ball and tries skills, even under pressure.', 'Always demands the ball; keeps trying things after failures.'),
('PSY-ALL-U10U11-4', 'U10-U11', 'psychological', 'all', 4, 'How much effort does the player show without being told?', 'Coasts or stops unless the coach is watching or prompting.', 'Works hard in bursts, mainly during fun or winning moments.', 'Puts in steady effort when reminded, but fades late on.', 'Works hard for most of the session on their own.', 'Sustains full effort throughout, driving themselves and others on.'),
('PSY-ALL-U12U13-1', 'U12-U13', 'psychological', 'all', 1, 'How does the player respond after making a mistake?', 'Head drops; the mistake affects their play for a long spell.', 'Gets frustrated and stops taking risks afterwards.', 'Recovers with encouragement, but confidence dips.', 'Refocuses quickly and stays in the game.', 'Uses it as motivation; responds with a positive action.'),
('PSY-ALL-U12U13-2', 'U12-U13', 'psychological', 'all', 2, 'Does the player stay concentrated for the whole game?', 'Switches off often; caught out ball-watching.', 'Concentrates only when directly involved.', 'Focused in key moments, lapses in quiet spells.', 'Stays concentrated for most of the game.', 'Fully switched on throughout; anticipates the next moment.'),
('PSY-ALL-U12U13-3', 'U12-U13', 'psychological', 'all', 3, 'Does the player stay composed under pressure?', 'Panics on the ball when opponents close in.', 'Rushes decisions when pressured, often losing possession.', 'Composed when time allows, hurried under pressure.', 'Stays calm and makes sound decisions under pressure.', 'Thrives under pressure; composure lifts those around them.'),
('PSY-ALL-U12U13-4', 'U12-U13', 'psychological', 'all', 4, 'Does the player drive their own effort and standards?', 'Needs constant pushing to work and apply themselves.', 'Works hard only when the coach is watching.', 'Applies themselves, but standards slip when tired.', 'Self-motivated; keeps standards high for most of the game.', 'Drives their own and teammates'' effort throughout.'),
('PSY-ALL-U14U15-1', 'U14-U15', 'psychological', 'all', 1, 'How does the player respond to setbacks during a game?', 'Visibly rattled; one setback derails their whole performance.', 'Dwells on setbacks; play drops for a long period.', 'Recovers eventually, but needs time to reset.', 'Responds well, staying competitive after setbacks.', 'Unshaken by setbacks; often responds with their best.'),
('PSY-ALL-U14U15-2', 'U14-U15', 'psychological', 'all', 2, 'Does the player maintain concentration under fatigue and pressure?', 'Loses focus badly when tired or under pressure.', 'Concentration drops noticeably in the closing stages.', 'Holds focus until fatigue sets in late.', 'Stays concentrated even when tired or pressured.', 'Sharpest in the biggest, most demanding moments.'),
('PSY-ALL-U14U15-3', 'U14-U15', 'psychological', 'all', 3, 'Does the player show composure in important moments?', 'Freezes or rushes when the moment matters.', 'Nervy in key moments; decisions suffer.', 'Handles most moments, wobbles in the biggest.', 'Composed and reliable when it matters most.', 'Wants the big moments; delivers under real pressure.'),
('PSY-ALL-U14U15-4', 'U14-U15', 'psychological', 'all', 4, 'Does the player take responsibility and set their own standards?', 'Avoids responsibility; blames others when things go wrong.', 'Does the minimum unless pushed by the coach.', 'Takes responsibility in patches, inconsistent under pressure.', 'Holds themselves accountable and sets high standards.', 'Leads by example; lifts the standards of others.'),
('PSY-ALL-U16U17-1', 'U16-U17', 'psychological', 'all', 1, 'How does the player respond to adversity in a match?', 'Crumbles under adversity; performance collapses when things go against them.', 'Struggles to reset; adversity visibly affects their game.', 'Recovers, but the response is inconsistent.', 'Meets adversity head-on and keeps performing.', 'Resilient under any adversity; raises their level when tested.'),
('PSY-ALL-U16U17-2', 'U16-U17', 'psychological', 'all', 2, 'Does the player sustain focus and decision-making for the whole game?', 'Concentration and decisions fall away as the game wears on.', 'Mental sharpness drops noticeably in the second half.', 'Holds focus well until the final stages.', 'Maintains sharp focus and decisions throughout.', 'Mentally relentless; as sharp at the end as the start.'),
('PSY-ALL-U16U17-3', 'U16-U17', 'psychological', 'all', 3, 'Does the player perform under real pressure?', 'Pressure clearly undermines their performance.', 'Performs in comfort, shrinks when pressure rises.', 'Copes with pressure in most situations.', 'Performs reliably under significant pressure.', 'Elevates their game when the pressure is highest.'),
('PSY-ALL-U16U17-4', 'U16-U17', 'psychological', 'all', 4, 'Does the player show leadership and ownership on the pitch?', 'Offers no leadership; withdraws when things get hard.', 'Leads only when the team is on top.', 'Shows leadership in flashes, not consistently.', 'Leads consistently and takes ownership of performance.', 'Drives the team; standards and mentality lift around them.'),
('SOC-ALL-U6U7-1', 'U6-U7', 'social', 'all', 1, 'Does the player share the ball and let others have a go?', 'Keeps the ball to themselves; won''t pass or share.', 'Shares only when told to by the coach.', 'Shares sometimes, but often wants the ball back.', 'Happily shares and lets teammates have a turn.', 'Loves setting others up; always includes teammates.'),
('SOC-ALL-U6U7-2', 'U6-U7', 'social', 'all', 2, 'Is the player kind and encouraging to teammates?', 'Unkind or sulky towards teammates when things go wrong.', 'Plays alongside others but rarely interacts kindly.', 'Friendly when reminded, but mostly focused on themselves.', 'Kind to teammates and cheers them on.', 'Always encouraging; makes teammates feel good.'),
('SOC-ALL-U6U7-3', 'U6-U7', 'social', 'all', 3, 'Does the player listen to the coach and follow instructions?', 'Doesn''t listen; carries on doing their own thing.', 'Listens briefly, then forgets the instruction.', 'Listens when spoken to directly.', 'Listens to the coach and tries to follow.', 'Listens carefully and does what''s asked straight away.'),
('SOC-ALL-U6U7-4', 'U6-U7', 'social', 'all', 4, 'Does the player play nicely and follow the rules?', 'Argues, pushes, or ignores the rules.', 'Follows rules only when watched closely.', 'Mostly plays fairly, occasional lapses.', 'Plays fairly and follows the rules.', 'Always fair; a good example to others.'),
('SOC-ALL-U8U9-1', 'U8-U9', 'social', 'all', 1, 'Does the player talk to and help teammates during play?', 'Silent; plays as if alone on the pitch.', 'Talks only to complain or blame teammates.', 'Occasionally calls for the ball, little else.', 'Talks to help teammates during the game.', 'Constant positive talk; helps teammates with information.'),
('SOC-ALL-U8U9-2', 'U8-U9', 'social', 'all', 2, 'Does the player encourage teammates, especially after a mistake?', 'Criticises or blames teammates when they make a mistake.', 'Stays quiet when a teammate makes a mistake.', 'Encourages sometimes, but not consistently.', 'Encourages teammates, especially after a mistake.', 'Always lifts teammates; first to support after errors.'),
('SOC-ALL-U8U9-3', 'U8-U9', 'social', 'all', 3, 'Does the player respect the coach, referee, and opponents?', 'Argues with officials or disrespects opponents.', 'Shows respect only when reminded.', 'Respectful most of the time, occasional lapses.', 'Respects officials, opponents, and the coach.', 'Model behaviour; respectful even when decisions go against them.'),
('SOC-ALL-U8U9-4', 'U8-U9', 'social', 'all', 4, 'Does the player put the team first?', 'Only interested in their own game.', 'Shares reluctantly; prefers to keep the ball.', 'Works for the team when it suits them.', 'Puts the team first in most situations.', 'Always team-first; celebrates others'' success as their own.'),
('SOC-ALL-U10U11-1', 'U10-U11', 'social', 'all', 1, 'Does the player communicate with teammates during the game?', 'Rarely speaks; gives teammates no information.', 'Talks only when frustrated or to complain.', 'Communicates in obvious moments, quiet otherwise.', 'Talks regularly to help and organise teammates.', 'Constant, useful communication; teammates rely on it.'),
('SOC-ALL-U10U11-2', 'U10-U11', 'social', 'all', 2, 'Does the player support teammates who are struggling?', 'Turns on teammates who make mistakes.', 'Ignores struggling teammates, focuses on self.', 'Offers support when it''s easy to.', 'Supports and encourages struggling teammates.', 'Rallies the team; nobody is left isolated.'),
('SOC-ALL-U10U11-3', 'U10-U11', 'social', 'all', 3, 'Does the player show respect and fair play when competing?', 'Argues with the referee and reacts badly to decisions.', 'Struggles to accept decisions that go against them.', 'Usually fair, but competitiveness sometimes spills over.', 'Competes hard while respecting officials and opponents.', 'Fierce competitor who always stays respectful and fair.'),
('SOC-ALL-U10U11-4', 'U10-U11', 'social', 'all', 4, 'Does the player accept their role and work for the team?', 'Refuses roles they don''t like; plays selfishly.', 'Does their own thing rather than the team''s plan.', 'Accepts a role, but drifts from it.', 'Accepts their role and works for the team.', 'Embraces any role to help the team win.'),
('SOC-ALL-U12U13-1', 'U12-U13', 'social', 'all', 1, 'Does the player organise and inform teammates during play?', 'Provides no information; teammates play blind around them.', 'Talks occasionally, but rarely anything useful.', 'Gives information in key moments only.', 'Regularly organises and informs those around them.', 'Directs teammates constantly; a real voice on the pitch.'),
('SOC-ALL-U12U13-2', 'U12-U13', 'social', 'all', 2, 'Does the player support the team''s morale and spirit?', 'Drags morale down; sulks or blames others.', 'Neutral presence; adds little to team spirit.', 'Lifts the group when things are going well.', 'Keeps morale up, even in tough moments.', 'Sets the tone; a positive force for the team.'),
('SOC-ALL-U12U13-3', 'U12-U13', 'social', 'all', 3, 'Does the player stay disciplined and respectful under pressure?', 'Loses discipline; argues, reacts, or retaliates.', 'Discipline slips when frustrated or losing.', 'Mostly disciplined, occasional lapses under pressure.', 'Stays disciplined and respectful under pressure.', 'Exemplary discipline; calms teammates in heated moments.'),
('SOC-ALL-U12U13-4', 'U12-U13', 'social', 'all', 4, 'Does the player put team success above personal glory?', 'Chases personal glory at the team''s expense.', 'Prioritises own game over the team''s needs.', 'Balances self and team inconsistently.', 'Puts team success ahead of personal glory.', 'Selfless; consistently sacrifices for the team.'),
('SOC-ALL-U14U15-1', 'U14-U15', 'social', 'all', 1, 'Does the player lead and communicate to influence teammates?', 'Offers no leadership; silent and disengaged from teammates.', 'Talks, but it rarely influences those around them.', 'Leads in flashes, mainly when things go well.', 'Communicates well and positively influences teammates.', 'A genuine leader; teammates respond to their voice.'),
('SOC-ALL-U14U15-2', 'U14-U15', 'social', 'all', 2, 'Does the player support teammates and the group culture?', 'Undermines the group; cliquey or divisive.', 'Keeps to themselves; adds little to culture.', 'Supports teammates they are close to only.', 'Supports the whole group and its culture.', 'Central to team culture; unites the group.'),
('SOC-ALL-U14U15-3', 'U14-U15', 'social', 'all', 3, 'Does the player manage their behaviour with officials and opponents?', 'Regularly disrespects officials or opponents.', 'Reacts poorly when decisions go against them.', 'Generally controlled, slips under real provocation.', 'Manages behaviour well with officials and opponents.', 'Composed and respectful even under heavy provocation.'),
('SOC-ALL-U14U15-4', 'U14-U15', 'social', 'all', 4, 'Does the player accept accountability within the team?', 'Blames teammates; never accepts their own part.', 'Reluctant to own mistakes in front of others.', 'Accepts accountability when it''s pointed out.', 'Readily owns mistakes and stays accountable.', 'Holds self and others accountable for standards.'),
('SOC-ALL-U16U17-1', 'U16-U17', 'social', 'all', 1, 'Does the player lead and set standards for the team?', 'Provides no leadership; sets a poor example.', 'Leads only occasionally and inconsistently.', 'Leads in key moments but not day to day.', 'Leads consistently and sets clear standards.', 'Defines the team''s standards; others follow their example.'),
('SOC-ALL-U16U17-2', 'U16-U17', 'social', 'all', 2, 'Does the player strengthen team unity and support others?', 'Divisive; damages relationships within the group.', 'Detached; contributes little to team unity.', 'Supports the group when convenient.', 'Actively strengthens unity and supports teammates.', 'The glue of the team; brings everyone together.'),
('SOC-ALL-U16U17-3', 'U16-U17', 'social', 'all', 3, 'Does the player show maturity with officials and opponents?', 'Immature; confronts officials and opponents readily.', 'Loses composure when provoked or aggrieved.', 'Usually mature, occasional lapses under pressure.', 'Consistently mature and respectful in conduct.', 'Exemplary conduct; represents the team impeccably.'),
('SOC-ALL-U16U17-4', 'U16-U17', 'social', 'all', 4, 'Does the player consistently put the team above themselves?', 'Self-interested; team comes a distant second.', 'Serves the team only when it suits them.', 'Mostly team-first, occasionally self-serving.', 'Consistently puts the team above themselves.', 'Utterly selfless; the team always comes first.')
on conflict (id) do nothing;
